language: node_js
sudo: required
node_js:
  - 8.11.3
branch: master
cache:
  directories:
    - node_modules
before_install:
    - export TZ='China/Shanghai'
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - chmod +x ./deploy.sh
script:
  - ./deploy.sh